#include "instruction.h"
#include "cpu_circuit.h"
#include "memory.h"
#include ""


instruction instruction_set[0x100] = {
  {BRK, ADDR_IMPLIED, 7, 1}, {ORA, ADDR_INDEX_INDIRECT, 6, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0}, {INST_UNDEF, ADDR_UNDEF, 0, 0}, 
  {INST_UNDEF, ADDR_UNDEF, 0, 0}, {ORA, ADDR_ZEROPAGE, 3, 2},{ASL, ADDR_ZEROPAGE, 5, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0}, 
  {PHP, ADDR_IMPLIED, 3, 1}, {ORA, ADDR_IMMEDIATE, 2, 2}, {ASL, ADDR_ACCUMULATOR, 2, 1}, {INST_UNDEF, ADDR_UNDEF, 0, 0}, 
  {INST_UNDEF, ADDR_UNDEF, 0, 0}, {ORA, ADDR_ABSOLUTE, 4, 3}, {ASL, ADDR_ABSOLUTE, 6, 3}, {INST_UNDEF, ADDR_UNDEF, 0, 0},

  {BPL, ADDR_RELATIVE, 2, 2}, {ORA, ADDR_INDIRECT_INDEX, 5, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0}, {INST_UNDEF, ADDR_UNDEF, 0, 0}, 
  {INST_UNDEF, ADDR_UNDEF, 0, 0}, {ORA, ADDR_INDEX_ZEROPAGE_X, 4, 2}, {ASL, ADDR_INDEX_ZEROPAGE_X, 6, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0}, 
  {CLC, ADDR_IMPLIED, 2, 1}, {ORA, ADDR_INDEX_ABSOLUTE_Y, 4, 3}, {INST_UNDEF, ADDR_UNDEF, 0, 0}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {INST_UNDEF, ADDR_UNDEF, 0, 0}, {ORA, ADDR_INDEX_ABSOLUTE_X, 4, 3}, {ASL, ADDR_INDEX_ABSOLUTE_X, 6, 3}, {INST_UNDEF, ADDR_UNDEF, 0, 0},

  {JSR, ADDR_ABSOLUTE, 6, 3}, {AND, ADDR_INDEX_INDIRECT, 6, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {BIT, ADDR_ZEROPAGE, 3, 2}, {AND, ADDR_ZEROPAGE, 3, 2}, {ROL, ADDR_ZEROPAGE, 5, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {PLP, ADDR_IMPLIED, 4, 1}, {AND, ADDR_IMMEDIATE, 2, 2}, {ROL, ADDR_ACCUMULATOR, 2, 1}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {BIT, ADDR_ABSOLUTE, 4, 3}, {AND, ADDR_ABSOLUTE, 4, 3}, {ROL, ADDR_ABSOLUTE, 6, 3}, {INST_UNDEF, ADDR_UNDEF, 0, 0},

  {BMI, ADDR_RELATIVE, 2, 2}, {AND, ADDR_INDIRECT_INDEX, 5, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {INST_UNDEF, ADDR_UNDEF, 0, 0}, {AND, ADDR_INDEX_ZEROPAGE_X, 4, 2}, {ROL, ADDR_INDEX_ZEROPAGE_X, 6, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {SEC, ADDR_IMPLIED, 2, 1}, {AND, ADDR_INDEX_ABSOLUTE_Y, 4, 3}, {INST_UNDEF, ADDR_UNDEF, 0, 0}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {INST_UNDEF, ADDR_UNDEF, 0, 0}, {AND, ADDR_INDEX_ABSOLUTE_X, 4, 3}, {ROL, ADDR_INDEX_ABSOLUTE_X, 6, 3}, {INST_UNDEF, ADDR_UNDEF, 0, 0},

  {RTI, ADDR_IMPLIED, 6, 1}, {EOR, ADDR_INDEX_INDIRECT, 6, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {INST_UNDEF, ADDR_UNDEF, 0, 0}, {EOR, ADDR_ZEROPAGE, 3, 2}, {LSR, ADDR_ZEROPAGE, 5, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {PHA, ADDR_IMPLIED, 4, 1}, {EOR, ADDR_IMMEDIATE, 2, 2}, {LSR, ADDR_ACCUMULATOR, 2, 1}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {JMP, ADDR_ABSOLUTE, 3, 3}, {EOR, ADDR_ABSOLUTE, 4, 3}, {LSR, ADDR_ABSOLUTE, 6, 3}, {INST_UNDEF, ADDR_UNDEF, 0, 0},

  {BVC, ADDR_RELATIVE, 2, 2}, {EOR, ADDR_INDIRECT_INDEX, 5, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {INST_UNDEF, ADDR_UNDEF, 0, 0}, {EOR, ADDR_INDEX_ZEROPAGE_X, 4, 2}, {LSR, ADDR_INDEX_ZEROPAGE_X, 6, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {CLI, ADDR_IMPLIED, 2, 1}, {EOR, ADDR_INDEX_ABSOLUTE_Y, 4, 3}, {INST_UNDEF, ADDR_UNDEF, 0, 0}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {INST_UNDEF, ADDR_UNDEF, 0, 0}, {EOR, ADDR_INDEX_ABSOLUTE_X, 4, 3}, {LSR, ADDR_INDEX_ABSOLUTE_X, 6, 3}, {INST_UNDEF, ADDR_UNDEF, 0, 0},

  {RTS, ADDR_IMPLIED, 6, 1}, {ADC, ADDR_INDEX_INDIRECT, 6, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {INST_UNDEF, ADDR_UNDEF, 0, 0}, {ADC, ADDR_ZEROPAGE, 3, 2}, {ROR, ADDR_ZEROPAGE, 5, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {PLA, ADDR_IMPLIED, 4, 1}, {ADC, ADDR_IMMEDIATE, 2, 2}, {ROR, ADDR_ACCUMULATOR, 2, 1}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {JMP, ADDR_ABSOLUTE_INDIRECT, 5, 3}, {ADC, ADDR_ABSOLUTE, 4, 3}, {ROR, ADDR_ABSOLUTE, 6, 3}, {INST_UNDEF, ADDR_UNDEF, 0, 0},

  {BVS, ADDR_RELATIVE, 2, 2}, {ADC, ADDR_INDIRECT_INDEX, 5, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {INST_UNDEF, ADDR_UNDEF, 0, 0}, {ADC, ADDR_INDEX_ZEROPAGE_X, 4, 2}, {ROR, ADDR_INDEX_ZEROPAGE_X, 6, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {SEI, ADDR_IMPLIED, 2, 1}, {ADC, ADDR_INDEX_ABSOLUTE_Y, 4, 3}, {INST_UNDEF, ADDR_UNDEF, 0, 0}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {INST_UNDEF, ADDR_UNDEF, 0, 0}, {ADC, ADDR_INDEX_ABSOLUTE_X, 4, 3}, {ROR, ADDR_INDEX_ABSOLUTE_X, 6, 3}, {INST_UNDEF, ADDR_UNDEF, 0, 0},

  {INST_UNDEF, ADDR_UNDEF, 0, 0}, {STA, ADDR_INDEX_INDIRECT, 6, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {STY, ADDR_ZEROPAGE, 3, 2}, {STA, ADDR_ZEROPAGE, 3, 2}, {STX, ADDR_ZEROPAGE, 3, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {DEY, ADDR_IMPLIED, 2, 1}, {INST_UNDEF, ADDR_UNDEF, 0, 0}, {TXA, ADDR_IMPLIED, 2, 1}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {STY, ADDR_ABSOLUTE, 4, 3}, {STA, ADDR_ABSOLUTE, 4, 3}, {STX, ADDR_ABSOLUTE, 4, 3}, {INST_UNDEF, ADDR_UNDEF, 0, 0},

  {BCC, ADDR_RELATIVE, 2, 2}, {STA, ADDR_INDIRECT_INDEX, 5, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {STY, ADDR_INDEX_ZEROPAGE_X, 4, 2}, {STA, ADDR_INDEX_ZEROPAGE_X, 4, 2}, {STX, ADDR_INDEX_ZEROPAGE_Y, 4, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {TYA, ADDR_IMPLIED, 2, 1}, {STA, ADDR_INDEX_ABSOLUTE_Y, 4, 3}, {TXS, ADDR_IMPLIED, 2, 1}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {INST_UNDEF, ADDR_UNDEF, 0, 0}, {STA, ADDR_INDEX_ABSOLUTE_X, 4, 3}, {INST_UNDEF, ADDR_UNDEF, 0, 0}, {INST_UNDEF, ADDR_UNDEF, 0, 0},

  {LDY, ADDR_IMMEDIATE, 2, 2}, {LDA, ADDR_INDEX_INDIRECT, 6, 2}, {LDX, ADDR_IMMEDIATE, 2, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {LDY, ADDR_ZEROPAGE, 3, 2}, {LDA, ADDR_ZEROPAGE, 3, 2}, {LDX, ADDR_ZEROPAGE, 3, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {TAY, ADDR_IMPLIED, 2, 1}, {LDA, ADDR_IMMEDIATE, 2, 2}, {TAX, ADDR_IMPLIED, 2, 1}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {LDY, ADDR_ABSOLUTE, 4, 3}, {LDA, ADDR_ABSOLUTE, 4, 3}, {LDX, ADDR_ABSOLUTE, 4, 3}, {INST_UNDEF, ADDR_UNDEF, 0, 0},

  {BCS, ADDR_RELATIVE, 2, 2}, {LDA, ADDR_INDIRECT_INDEX, 5, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {LDY, ADDR_INDEX_ZEROPAGE_X, 4, 2}, {LDA, ADDR_INDEX_ZEROPAGE_X, 4, 2}, {LDX, ADDR_INDEX_ZEROPAGE_Y, 4, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {CLV, ADDR_IMPLIED, 2, 1}, {LDA, ADDR_INDEX_ABSOLUTE_Y, 4, 3}, {TSX, ADDR_IMPLIED, 2, 1}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {LDY, ADDR_INDEX_ABSOLUTE_X, 4, 3}, {LDA, ADDR_INDEX_ABSOLUTE_X, 4, 3}, {LDX, ADDR_INDEX_ABSOLUTE_Y, 4, 3}, {INST_UNDEF, ADDR_UNDEF, 0, 0},

  {CPY, ADDR_IMMEDIATE, 2, 2}, {CMP, ADDR_INDEX_INDIRECT, 6, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {CPY, ADDR_ZEROPAGE, 3, 2}, {CMP, ADDR_ZEROPAGE, 3, 2}, {DEC, ADDR_ZEROPAGE, 5, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {INY, ADDR_IMPLIED, 2, 1}, {CMP, ADDR_IMMEDIATE, 2, 2}, {DEX, ADDR_IMPLIED, 2, 1}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {CPY, ADDR_ABSOLUTE, 4, 3}, {CMP, ADDR_ABSOLUTE, 4, 3}, {DEC, ADDR_ABSOLUTE, 6, 3}, {INST_UNDEF, ADDR_UNDEF, 0, 0},

  {BNE, ADDR_RELATIVE, 2, 2}, {CMP, ADDR_INDIRECT_INDEX, 5, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {INST_UNDEF, ADDR_UNDEF, 0, 0}, {CMP, ADDR_INDEX_ZEROPAGE_X, 4, 2}, {DEC, ADDR_INDEX_ZEROPAGE_X, 6, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {CLD, ADDR_IMPLIED, 2, 1}, {CMP, ADDR_INDEX_ABSOLUTE_Y, 4, 3}, {INST_UNDEF, ADDR_UNDEF, 0, 0}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {INST_UNDEF, ADDR_UNDEF, 0, 0}, {CMP, ADDR_INDEX_ABSOLUTE_X, 4, 3}, {DEC, ADDR_INDEX_ABSOLUTE_X, 6, 3}, {INST_UNDEF, ADDR_UNDEF, 0, 0},

  {CPX, ADDR_IMMEDIATE, 2, 2}, {SBC, ADDR_INDEX_INDIRECT, 6, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {CPX, ADDR_ZEROPAGE, 3, 2}, {SBC, ADDR_ZEROPAGE, 3, 2}, {INC, ADDR_ZEROPAGE, 5, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {INX, ADDR_IMPLIED, 2, 1}, {SBC, ADDR_IMMEDIATE, 2, 2}, {NOP, ADDR_IMPLIED, 2, 1}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {CPX, ADDR_ABSOLUTE, 4, 3}, {SBC, ADDR_ABSOLUTE, 4, 3}, {INC, ADDR_ABSOLUTE, 6, 3}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  
  {BEQ, ADDR_RELATIVE, 2, 2}, {SBC, ADDR_INDIRECT_INDEX, 5, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {INST_UNDEF, ADDR_UNDEF, 0, 0}, {SBC, ADDR_INDEX_ZEROPAGE_X, 4, 2}, {INC, ADDR_INDEX_ZEROPAGE_X, 6, 2}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {SED, ADDR_IMPLIED, 2, 1}, {SBC, ADDR_INDEX_ABSOLUTE_Y, 4, 3}, {INST_UNDEF, ADDR_UNDEF, 0, 0}, {INST_UNDEF, ADDR_UNDEF, 0, 0},
  {INST_UNDEF, ADDR_UNDEF, 0, 0}, {SBC, ADDR_INDEX_ABSOLUTE_X, 4, 3}, {INC, ADDR_INDEX_ABSOLUTE_X, 6, 3}, {INST_UNDEF, ADDR_UNDEF, 0, 0}
};